# Generated by Django 6.0.7 on 2026-07-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='linkedin_url',
        ),
    ]
